### ISSUE TITLE
head.use is not a function

### ISSUE THREAD

**Issue by Barbapapazes** [harlan-zw/unhead-schema-org#1]
### Describe the bug

Hello, just update my module but can't know what happened
![image](https://user-images.githubusercontent.com/45267552/206788458-c9dcf035-fdb9-4de3-b37a-110d5dd9ab95.png)

### Reproduction

https://github.com/Barbapapazes/le-classement.fr/pull/79

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
    Memory: 3.15 GB / 15.88 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.42), ChromiumDev (109.0.1495.2)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hi, please delete lock file / node_modules and re install. You need the latest @vueuse/head version

**Comment by Barbapapazes** [comment]
Hello,

I just see the lastest release of @vueuse/head but because Nuxt3 use it internally, I have to way that the Nuxt team update it and release it ?

**Comment by harlan-zw** [comment]
Nuxt has a caret dependency of @vueuse/head, so when you delete your lock file / node_modules and re-install, it will use the latest patch release

Did you try it?

**Comment by Barbapapazes** [comment]
It works perfectly, thanks a lot for your works!
