### ISSUE TITLE
Add support for Job posting Schema

### ISSUE THREAD

**Issue by sanderdewinter** [harlan-zw/unhead-schema-org#10]
### Clear and concise description of the problem

There is currently no support for schema [JobPosting](https://schema.org/JobPosting). Are there any future plans to support this? If not I might create some time to write a PR.

Thanks for to great work so far.

### Suggested solution

Implement job posting schema according to [schema.org](https://schema.org/JobPosting) and [Google structured data guidelines](https://developers.google.com/search/docs/appearance/structured-data/job-posting)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by harlan-zw** [comment]
Hey, happy to get this up and running in the next few days. 

I noticed you forked the repo though, so if you were planning to send a PR I'll hold off?

**Comment by sanderdewinter** [comment]
Thanks for your help! I was indeed trying to get something up and running. I will try create a draft PR in coming days which will include the fields of the schema I was looking for. If I do not succeed I might need a little help if possible :)

**Comment by harlan-zw** [comment]
Sounds good, more than happy to answer any questions you may have in this issue or on discord (if you use it).

If you just need to get something up and running quickly you can always provide raw json to useSchemaOrg too.
