### ISSUE TITLE
`defineQuestion` FAQ schema syntax is generated wrong when using it with `.map`

### ISSUE THREAD

**Issue by madebyfabian** [harlan-zw/unhead-schema-org#12]
### Describe the bug

Creating a FAQ schema like in the docs https://unhead-schema-org.harlanzw.com/guide/recipes/faq, I noticed that the generated syntax is wrong as soon as you try to generate it dynamically. When checking it with the testing tool, it throws errors. https://validator.schema.org/.

Since FAQ data is almost always dynamic, here is what I did:

```ts
const data = [
  {
    name: 'How long is a piece of string?',
    acceptedAnswer:
      'The length of a piece of string is the number of characters in the string.',
  },
  {
    name: 'How big is a giraffe?',
    acceptedAnswer: 'A giraffe is 12 feet tall',
  },
];

useSchemaOrg([
  defineWebPage({
    '@type': 'FAQPage',
  }),
  ...data.map((entry) => {
    return entry;
  }),
]);
```

the data is normally coming from an API. But it seems that this approach is not possible with the module, right? When using it statically like in the docs, without any `.map`, it works though.

### Reproduction

https://stackblitz.com/edit/github-3hg9qc?file=app.vue,nuxt.config.ts

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (6) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by madebyfabian** [comment]
Just noticed I forgot a line, nevermind. Everything works 😄

**Comment by harlan-zw** [comment]
> Just noticed I forgot a line, nevermind. Everything works smile

Glad you could sort it out :)
