### ISSUE TITLE
`defineSearchAction` results in invalid potential actions schema

### ISSUE THREAD

**Issue by joshwcorbett** [harlan-zw/unhead-schema-org#15]
### Describe the bug

By following the docs on how to add a search box to my rich results, this package seems to have generated some schema that is very strange in comparison to sites with working search boxes.
```ts
useSchemaOrg([
  defineOrganization({...}),
  defineWebSite({
    potentialAction: [
	  defineSearchAction({
        target: '/search?q={search_term_string}',
      })
    ],
  }),
])
```
Resulting schema (not working):
```
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@id": "https://flagnorfail.com/#identity",
      "@type": "Organization",
      "description": "Limited Hand Printed Apparel. I Shall Not Flag Nor Fail.",
      "name": "FLAG NOR FAIL",
      "url": "https://flagnorfail.com",
    },
    {
      "@id": "https://flagnorfail.com/#website",
      "@type": "WebSite",
      "url": "https://flagnorfail.com",
      "potentialAction": [
        {
          "@type": "SearchAction",
          "target": {
            "@type": "EntryPoint",
            "urlTemplate": "https://flagnorfail.com/search?q={search_term_string}"
          },
          "query-input": {
            "@type": "PropertyValueSpecification",
            "valueRequired": true,
            "valueName": "search_term_string"
          }
        }
      ],
    },
  ]
}
```

Compare this output to nike (working search):
```
{
  "@context":"http://schema.org",
  "@type":"WebSite",
  "@id":"https://www.nike.com/#website",
  "url":"https://www.nike.com/",
  "name":"Nike",
  "potentialAction": {
    "@type":"SearchAction",
    "target":"https://www.nike.com/w?q={search_term_string}&vst={search_term_string}&cp=91120261542_sea_",
    "query-input":"required name=search_term_string"
  }
}
```

### Reproduction

https://flagnorfail.com

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
    Memory: 520.72 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/Library/pnpm/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/Library/pnpm/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox Developer Edition: 110.0
    Safari: 16.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey @joshwcorbett Thanks for the issue!

Looking at the site and the schema, it all looks correct though. The schema generation is based on Yoast and Google recommendations. 

You can see in the Rich Results Test it's passing for Sitelinks Searchbox https://search.google.com/test/rich-results/result?id=V2kuGVvrEj8uhQK5HV4CFQ

![image](https://user-images.githubusercontent.com/5326365/216508531-672dc2b7-ab65-428d-b964-705903fd29d3.png)

Would you mind providing some more context on why you think it's not working

**Comment by harlan-zw** [comment]
Going to close off, feel free to re-open if you have any input
