### ISSUE TITLE
Generate FAQs from list object

### ISSUE THREAD

**Issue by toniengelhardt** [harlan-zw/unhead-schema-org#17]
### Details

Not sure if this is the correct way, but after some tinkering I found this solution to generate the schema for a list of FAQs automatically:

```ts
const schema = [
  defineBreadcrumb({
    itemListElement: [
      { name: 'Home', item: '/' },
      { name: 'FAQ' },
    ],
  }),
]

faqList.forEach((faq) => {
  const _faq = defineQuestion({
    name: faq.question,
    acceptedAnswer: faq.answer,
  })
  schema.push(() => _faq)
})

useSchemaOrg(schema)
```

The intuitive solution of just inlining it doesn't seem to work:

```ts
useSchemaOrg([
  defineBreadcrumb({
    itemListElement: [
      { name: 'Home', item: '/' },
      { name: 'FAQ' },
    ],
  }),
  faqList.map(faq => defineQuestion({
    name: faq.question,
    acceptedAnswer: faq.answer,
  })
])
```

Maybe this could be added to the docs since I think it is a common use case to avoid duplicating the questions and answers?

**Comment by harlan-zw** [comment]
Hey @toniengelhardt 

I think the issue is that you're just providing an array entry to useSchemaOrg, it needs record entries.

If you change the code like this, it should work. If not happy to find a solution

```diff
useSchemaOrg([
  defineBreadcrumb({
    itemListElement: [
      { name: 'Home', item: '/' },
      { name: 'FAQ' },
    ],
  }),
-  faqList.map(faq => defineQuestion({
+ ...faqList.map(faq => defineQuestion({ 
    name: faq.question,
    acceptedAnswer: faq.answer,
  })
])
```

**Comment by toniengelhardt** [comment]
Ah, you're right, I forgot to destructure 🙈 

Sorry for bothering, closing...

**Comment by harlan-zw** [comment]
No problem at all :)
