### ISSUE TITLE
How to overwrite "@type": "Article" to  "@type": "BlogPosting",

### ISSUE THREAD

**Issue by Croodo** [harlan-zw/unhead-schema-org#4]
### Clear and concise description of the problem

There is no option to set the type as BlogPosting, is there any way to overwrite the default type?
I'm using the module for NuxtJs

### Suggested solution

Can't provide any solution 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by harlan-zw** [comment]
Hey @Croodo 

See here https://unhead-schema-org.harlanzw.com/guide/recipes/blog#specifying-the-article-type, you can augment the type however you like.

Let me know if you have issues with that

**Comment by harlan-zw** [comment]
Hey @Croodo 

Looks like the `BlogPosting` type was missing. I've added that in now. There isn't a separate `defineBlogPosting` utility as that would get verbose very quickly.

Instead, you can just augment the type like it's shown here https://unhead-schema-org.harlanzw.com/guide/recipes/blog#specifying-the-article-type

Let me know if you have any questions on that

**Comment by Croodo** [comment]
Adding "@type" : "BlogPosting" resolve it as an array, I guess we need to specify only one @type when using BlogPosting?

**Comment by harlan-zw** [comment]
Array is valid per the schema.org spec and is recommended by Yoast.

If you notice issues with it though let me know

**Comment by Croodo** [comment]
OK Thanks, for now, I'm gonna use it as an array. But please try to add defineBlogPosting as soon as possible.

**Comment by harlan-zw** [comment]
Hmm I'd rather not add it if this is valid. I'd accept a PR though
