### ISSUE TITLE
docs(github): discord invite code invalid

### ISSUE THREAD

**Issue by dargmuesli** [harlan-zw/unhead-schema-org#8]
### Describe the bug

The issue template links to a Discord invite code which seems to be invalid. I'd expect it to be valid or have GitHub discussions available to be able to ask questions for which a bug ticket might not be the proper medium.

### System Info

```Shell
n/a
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey, thanks for flagging this! I've fixed the discord link and I've added a new issue item for "Question / other", as discussions are not enabled for a number of my repos.
